import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Info() {
  return (
    <div className={styles.container}>
      <Head>
        <title>bytemaps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Info Page</h1>
      <p>
        Bytemaps is blahblah blah fuckin blah my e-mail is bytemaps@gmail.com
      </p>
    </div>
  )
}
