import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { client } from '../lib/apollo'
import { gql } from '@apollo/client'

const inter = Inter({ subsets: ['latin'] })

export default function Info({ page }) {
  if (!page) {
    return (
      <div className={styles.container}>
        <Head>
          <title>bytemaps | Error</title>
        </Head>
        <h1>Error: Page not found</h1>
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>bytemaps | {page.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{page.title}</h1>
      <p>
        Bytemaps is blahblah blah fuckin blah my e-mail is bytemaps@gmail.com
      </p>
    </div>
  )
}

export async function getStaticProps() {
  const GET_INFO_PAGE_BY_URI = gql`
    query GetInfoPageByUri($uri: String) {
      pageBy(uri: $uri) {
        title
        content
      }
    }
  `
  const { data } = await client.query({
    query: GET_INFO_PAGE_BY_URI,
    variables: {
      uri: '/info', // join the slug array into a URL path string
    },
  })

  return {
    props: {
      page: data.pageBy,
    },
  }
}
